appVersion: latest
image:
  app: ghcr.io/tim-hat-die-hand-an-der-maus/imdb-resolver

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

service:
  name: imdb
