apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    name: doppler-tim
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom:
    - find:
        path: "RESOLVER_IMDB_"
      rewrite:
        - regexp:
            source: "RESOLVER_IMDB_(.+)"
            target: "$1"

