apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    name: scaleway-tim-resolver-imdb
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
