name: Build/Publish docker image

on:
  push:
    branches:
      - '!master'

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: OpenAlcoholics/github-action-helm@v0.1.5
        with:
          raw_command: lint
      - uses: OpenAlcoholics/github-action-helm@v0.1.5
        with:
          raw_command: lint --strict

  test:
    name: "pytest"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pytest
        run: python -m pip install --upgrade pytest==7.1.2
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run test suite
        run: pytest

  build_push_docker:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/tim-hat-die-hand-an-der-maus/imdb-resolver:${GITHUB_SHA} .
