name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  clean:
    concurrency: cleanup
    permissions:
      packages: write
    uses: tim-hat-die-hand-an-der-maus/actions-container/.github/workflows/clean.yml@v7
    with:
      min-versions-to-keep: '0'
