name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1
